### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by LamnouarMohamed** [ankitbko/vision-on-edge#1]
Hi,

I hope all is fine with you? 
Thank you so much for sharing this repository, I have two questions:

1)- I need to reverse your concept from two Observable, and one observer, like I have two cameras and one object detection, I need to get two frames and concatenate them after that pass it to object detection I need it with rxpython any suggestion for it, thank you 
2)-  second question relate to code below what is the difference between 

`
op.map(
                lambda frame: Frame(
                    cv2.resize(frame.frame, frame_size),
                    frame.correlation_id,
                )
)
`
and this 

`
 op.map(
                lambda frame: Frame(
                    frame.frame,
                    frame.correlation_id,
                )
`
I guess if I understand it's same.
`

    def _emit_frame_to_socket(self, frame_stream: Observable, socket_fps: float, frame_size: list) -> Observable:
        """"
        Emit frame to socket.

        @param
            frame_stream (Observable): Frame stream object
            frame_size (list): Frame size for socket (width, height)
        @return
            frame_stream (Observable): Frame stream object
       """"
        return frame_stream.pipe(
            op.sample(socket_fps),
            op.map(
                lambda frame: Frame(
                    cv2.resize(frame.frame, frame_size),
                    frame.correlation_id,
                )
            ),
            op.map(
                lambda frame: Frame(
                    frame.frame,
                    frame.correlation_id,
                )
            ),
            op.map(lambda frame: self._write_to_socket(frame=frame)),
        )

`

**Comment by ankitbko** [comment]
@LamnouarMohamed 
1. There are many [*combining* operators](https://rxpy.readthedocs.io/en/latest/operators.html#combining-observables) in rxpy that can combine two different observables into one.  Maybe try the [zip](https://rxpy.readthedocs.io/en/latest/reference_operators.html#reactivex.operators.zip) operator.
2. Good catch. Must be leftover code from code cleanup.

**Comment by LamnouarMohamed** [comment]
@ankitbko  Thank you for response

**Comment by LamnouarMohamed** [comment]
@ankitbko  sorry about annoying 

3)- **I didn't understand why you don't use subscribe,** I have seen reading from queue for process Object Detection, and also same thing for part UI, I didn't understand why you don't use subscribe on this part. (maybe I don't understand, or maybe my question is wrong I will try to wait you're response, and if my question is correct can you help me to put this part on subscribe)

Thank you
Mohamed

**Comment by ankitbko** [comment]
https://github.com/ankitbko/vision-on-edge/blob/main/common/frame_provider.py#L239

I did not understand your question. Is this not the Subscribe you are talking about?
